# Generated by Django 2.2.24 on 2021-09-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecomuser',
            name='tenant_admin',
            field=models.BooleanField(default=False),
        ),
    ]
